[workspace]
authors = ["kozo <kozoYang@outlook.com>"]
channels = ["rapidsai",
            "https://prefix.dev/meta-forge",
            "conda-forge"]
name = "bootstraper"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
libc = { family = "glibc", version = "2.34" }
cuda = "12.7"

[dependencies]
seastar-dev = ">=2025.5.20"
libboost-devel = "*"
gnutls = "*"
liburing = "*"
libhwloc = "*"
libsctp-dev = "*"
folly = "*"
yaml-cpp = "*"
glog = "*"
zlib = "*"
liblzma-devel = "*"
gdb = "*"
benchmark = "*"

[target.linux-64.dependencies]
cmake = "*"
make = "*"
cxx-compiler = "*"
c-compiler = "*"
rattler-build = "*"
rmm = "*"
cuda = "*"
ucxx = "*"
ucx = "*"
sysroot_linux-64 = "2.34.*"
fmt = "*"
